### PR TITLE
tests: Avoid Eq Float, use Rational

### PR DESCRIPTION
**Pull request by roberth**
Turns out Eq Float is not reliable. It happens to work for the combination of the numbers used and the floating point implementation on native haskell, at least x86_64, but it broke the tests on GHCJS.

```
$ node
> (1 + 0.1) * 100000
110000.00000000001
```

I can't blame GHCJS because the report doesn't really specify Float semantics.

This PR replaces Float by Rational, so that the Float implementation won't break syb tests anymore.

### CODE REVIEW

**Comment by roberth** [comment]
Hey @dreixel, this change is super simple but makes quite a difference :)

**Comment by sergv** [comment]
@roberth thanks for the PR. It looks like some tests are broken https://travis-ci.org/dreixel/syb/jobs/403169778, but it's not shown on this page. Could you please take a look? Also, if you rebase your branch the travis badge would probably appear on the github PR page.

**Comment by roberth** [comment]
I've rebased it and the tests succeed locally

**Comment by sergv** [comment]
Thanks, that's great. But I see some failures on CI - could you check them out, please?

**Comment by ddssff** [comment]
Unfortunately the failure is due to a failed unit test in several versions of ghc-7.6, but the log message is cut off.  Maybe we could just retire those compiler versions.

**Comment by sergv** [comment]
The 7.6 iss pretty outdated, true, but on the other hand it was working all this time and now the proposed solution is to just throw it away without any investigation. That feels a bit rushed.

**Comment by ddssff** [comment]
It might be easy if the whole message was visible, but without that it means resurrecting the compiler, unless someone knows a better way.  I figure people using 7.6 could probably make do with 7.4, 7.2, or 7.0.   :-D

**Comment by Bodigrim** [comment]
> Unfortunately the failure is due to a failed unit test in several versions of ghc-7.6, but the log message is cut off.

It is not cut off, it is just that `Data.Data.fromConstr` does not provide any helpful diagnostic:
https://hackage.haskell.org/package/base-4.14.1.0/docs/src/Data.Data.html#fromConstr

Note that `instance Data Ratio` is known to be broken for GHC < 8.0: https://gitlab.haskell.org/ghc/ghc/-/issues/10011

Unless someone is eager to investigate what exactly went wrong, I suggest to use `Int` instead of `Float` / `Ratio`.

**Comment by Bodigrim** [comment]
The least disruptive option is just to replace 0.1 by 0.125 or 0.25 or 0.5 or even 1 (or other number having exact binary representation) in 
https://github.com/dreixel/syb/blob/95798bd73bc431e67b462573d181f9e0ab0dc497/tests/Paradise.hs#L27

**Comment by sergv** [comment]
Given that #29 is merged, I think the issue is resolved and I'm closing this PR. If you feel the issue is still not resolved - please reopen, create a new one or raise an issue.

**Pull request closed without merging**
